### ISSUE TITLE
Width specifiers aren't respected for RedactableString

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/redact#17]
In https://github.com/cockroachdb/pebble/pull/1120 I found that formatting a `RedactableString` argument with a width specifier seems to ignore the width. Using a `SafeString` seems to work as expected.

**Comment by knz** [comment]
Ok so after much analysis and thought (and considering the changes needed for #19) I've decided what this is working as expected. `RedactableString` and `RedactableBytes` will get the special behavior, and we'll need `SafeString` to get output customizability.
