### ISSUE TITLE
HelperForErrorf cuts off trailing whitespaces from arguments

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/redact#18]
It seems like `HelperForErrorf` cuts off trailing whitespaces from its format arguements.

```
rs, _ := redact.HelperForErrorf("%s%s", " trailing white space test   ", "hello")
println(rs)

Outputs: 
‹ trailing white space test›‹hello›
```

Notice that the 3 spaces behind the first arg are cutoff.

May be related to https://github.com/cockroachdb/redact/issues/17

**Comment by knz** [comment]
@RichardJCai can you explain where this came up?

Right now, the elimination of trailing spaces and newlines for unsafe strings is a feature (it has been ever since the library was created).  We could reconsider, if there's a compelling use case.

**Comment by RichardJCai** [comment]
> @RichardJCai can you explain where this came up?
> 
> Right now, the elimination of trailing spaces and newlines for unsafe strings is a feature (it has been ever since the library was created). We could reconsider, if there's a compelling use case.

I don't think there is a compelling use case. From what I remember, I found a workaround to what I was doing.
